#pragma once

#ifndef PLAYER_H
#define PLAYER_H

#include "active_sound.h"
#include "audiobuffer/audiobuffer.h"
#include "audiobuffer/buffer.h"
#include "audiobuffer/metadata_ffi.h"
#include "enums.h"
#include "filters/filters.h"
#include "soloud/include/soloud.h"
#include "soloud/include/soloud_speech.h"
#include "soloud/src/backend/miniaudio/miniaudio.h"
#include "soloud_bus.h"

#include <atomic>
#include <iostream>
#include <map>
#include <memory>
#include <mutex>
#include <thread>
#include <vector>

struct PlaybackDevice {
  char *name;
  unsigned int isDefault;
  unsigned int id;
  ma_device_id deviceId;  // Store the actual device ID, not just the index
};

class Player {
public:
  Player();
  ~Player();

  /// @brief Initialize the player. Must be called before any other player
  /// functions.
  PlayerErrors init(unsigned int sampleRate, unsigned int bufferSize,
                    unsigned int channels, int deviceID = -1);

  /// @brief Change the playback device.
  PlayerErrors changeDevice(int deviceID);

  std::vector<PlaybackDevice> listPlaybackDevices();

  /// @brief Set a function callback triggered when a voice is stopped/ended.
  void setVoiceEndedCallback(void (*voiceEndedCallback)(unsigned int *));

  /// @brief Set a function callback triggered when the state of the player
  /// changes.
  void setStateChangedCallback(void (*stateChangedCallback)(unsigned int));

  /// @brief Must be called when there is no more need of the player or when
  /// closing the app.
  void dispose();

  /// @brief Return true if the player has been initialized.
  bool isInited();

  /// @brief Return the active sounds.
  int getSoundsCount();

  /// @brief Returns human readable string of an error.
  const std::string getErrorString(PlayerErrors errorCode) const;

  /// @brief Load a new sound to be played once or multiple times later.
  PlayerErrors loadFile(const std::string &completeFileName,
                        const bool loadIntoMem, unsigned int *hash);

  /// @brief Load a new sound stored into [mem] to be played once or multiple
  /// times later.
  PlayerErrors loadMem(const std::string &uniqueName, unsigned char *mem,
                       int length, bool loadIntoMem, unsigned int &hash);

  /// @brief Set up an audio stream.
  PlayerErrors
  setBufferStream(unsigned int &hash, unsigned long maxBufferSize,
                  BufferingType bufferingType, SoLoud::time bufferingTimeNeeds,
                  PCMformat pcmFormat = {44100, 2, 4, PCM_F32LE},
                  dartOnBufferingCallback_t onBufferingCallback = nullptr,
                  dartOnMetadataCallback_t onMetadataCallback = nullptr);

  /// @brief Resets the buffer of the data stream.
  PlayerErrors resetBufferStream(unsigned int hash);

  /// @brief Set the mp3 and Flac buffer icy meta int.
  PlayerErrors setBufferIcyMetaInt(unsigned int hash, int icyMetaInt);

  /// @brief Get the time consumed by the data stream of type
  /// `BufferingType.RELEASED`.
  PlayerErrors getStreamTimeConsumed(unsigned int hash, float *timeConsumed);

  /// @brief Add an audio data stream.
  PlayerErrors addAudioDataStream(unsigned int hash, const unsigned char *data,
                                  unsigned int aDataLen);

  /// @brief Set the end of the data stream.
  PlayerErrors setDataIsEnded(unsigned int hash);

  /// @brief Get the current buffer size in bytes of this sound with hash [hash].
  PlayerErrors getBufferSize(unsigned int hash, unsigned int *sizeInBytes);

  /// @brief Load a new sound which will be generated by the given params.
  PlayerErrors loadWaveform(int waveform, bool superWave, float scale,
                            float detune, unsigned int &hash);

  /// @brief Load a LibPD audio source for real-time DSP processing.
  PlayerErrors loadLibPDSource(unsigned int sampleRate, unsigned int channels,
                               unsigned int &hash);

  /// @brief If this sound is you can change the scale at runtime.
  void setWaveformScale(unsigned int soundHash, float newScale);

  /// @brief If this sound is you can change the detune at runtime.
  void setWaveformDetune(unsigned int soundHash, float newDetune);

  /// @brief Set the frequency of the given sound.
  void setWaveformFreq(unsigned int soundHash, float newFreq);

  /// @brief Set the given sound as a super wave.
  void setWaveformSuperwave(unsigned int soundHash, bool superwave);

  /// @brief Set a waveform type to the given sound.
  void setWaveform(unsigned int soundHash, int newWaveform);

  /// @brief Switch pause state for an already loaded sound identified by [handle].
  void pauseSwitch(unsigned int handle);

  /// @brief Pause or unpause already loaded sound identified by [handle].
  void setPause(unsigned int handle, bool pause);

  /// @brief Gets the pause state.
  bool getPause(unsigned int handle);

  /// @brief Set a sound's relative play speed.
  void setRelativePlaySpeed(unsigned int handle, float speed);

  /// @brief Get a sound's relative play speed.
  float getRelativePlaySpeed(unsigned int handle);

  /// @brief Gets the approximate volume for output per output channel.
  float getApproximateVolume(unsigned int channel);

  /// @brief Play already loaded sound identified by [soundHash].
  PlayerErrors play(unsigned int soundHash, unsigned int &handle,
                    unsigned int busId = 0,
                    float volume = 1.0f, float pan = 0.0f, bool paused = false,
                    bool looping = false, double loopingStartAt = 0.0);

  /// @brief Stop already loaded sound identified by [handle] and clear it.
  void stop(unsigned int handle);

  /// @brief Remove the unique [handle] form the list of internal sounds.
  void removeHandle(unsigned int handle);

  /// @brief Stop all handles of the already loaded sound identified by
  /// [soundHash] and clear it.
  void disposeSound(unsigned int soundHash);

  /// @brief Dispose all sounds already loaded.
  void disposeAllSound();

  /// @brief Clear every native->Dart callback pointer held by the player.
  void clearDartCallbackRegistrations();

  /// @brief Ask whether a sound is set to loop or not.
  bool getLooping(unsigned int handle);

  /// @brief This function can be used to set a sample to play on repeat.
  void setLooping(unsigned int handle, bool enable);

  /// @brief Get sound loop point value.
  double getLoopPoint(unsigned int handle);

  /// @brief Set sound loop point value.
  void setLoopPoint(unsigned int handle, double time);

  /// @brief Speech the given text.
  PlayerErrors textToSpeech(const std::string &textToSpeech,
                            unsigned int &handle);

  /// @brief Enable or disable visualization.
  void setVisualizationEnabled(bool enabled);

  /// @brief Returns true if the visualization is enabled.
  bool isVisualizationEnabled();

  /// @brief Calculates FFT of the currently playing sound.
  float *calcFFT(bool *isTheSameAsBefore);

  /// @brief Gets 256 samples of the currently playing sound.
  float *getWave(bool *isTheSameAsBefore);

  /// @brief get the sound length in seconds.
  double getLength(unsigned int soundHash);

  /// @brief Seek playing in seconds.
  PlayerErrors seek(SoLoud::handle handle, float time);

  /// @brief Get current sound position in seconds.
  double getPosition(SoLoud::handle handle);

  /// @brief Get current global volume.
  float getGlobalVolume();

  /// @brief Set the global volume for all the sounds.
  void setGlobalVolume(float volume);

  /// @brief Get current [handle] volume.
  float getVolume(SoLoud::handle handle);

  /// @brief Set the [handle] volume.
  void setVolume(SoLoud::handle handle, float volume);

  /// @brief Get a sound's current pan setting.
  float getPan(SoLoud::handle handle);

  /// @brief Set a sound's current pan setting.
  void setPan(SoLoud::handle handle, float pan);

  /// @brief Set the left/right volumes directly.
  void setPanAbsolute(SoLoud::handle handle, float panLeft, float panRight);

  /// @brief Check if a handle is still valid.
  bool isValidHandle(SoLoud::handle handle);

  /// @brief Return the number of active voices summing up all the handles of
  /// each sound.
  unsigned int getActiveVoiceCount_internal();

  /// @brief Returns the number of concurrent sounds that are playing a specific
  /// audio source.
  int countAudioSource(unsigned int soundHash);

  /// @brief Returns the number of voices the application has told SoLoud to
  /// play.
  unsigned int getVoiceCount();

  /// @brief Get a sound's protection state.
  bool getProtectVoice(SoLoud::handle handle);

  /// @brief Set a sound's protection state.
  void setProtectVoice(SoLoud::handle handle, bool protect);

  /// @brief Set the inaudible behavior of a live sound.
  void setInaudibleBehavior(SoLoud::handle handle, bool mustTick, bool kill);

  /// @brief Get the current maximum active voice count.
  unsigned int getMaxActiveVoiceCount();

  /// @brief set the current maximum active voice count.
  void setMaxActiveVoiceCount(unsigned int maxVoiceCount);

  /// @brief Find a sound by its handle.
  ActiveSound *findByHandle(SoLoud::handle handle);

  /// @brief Find a sound by its handle.
  ActiveSound *findByHash(unsigned int hash);

  void debug();

  /////////////////////////////////////////
  /// voice groups
  /////////////////////////////////////////

  unsigned int createVoiceGroup();
  void destroyVoiceGroup(SoLoud::handle handle);
  void addVoiceToGroup(SoLoud::handle voiceGroupHandle,
                       SoLoud::handle voiceHandle);
  bool isVoiceGroup(SoLoud::handle handle);
  bool isVoiceGroupEmpty(SoLoud::handle handle);

  /////////////////////////////////////////
  /// faders & oscillators
  /////////////////////////////////////////

  void fadeGlobalVolume(float to, float time);
  void fadeVolume(SoLoud::handle handle, float to, float time);
  void fadePan(SoLoud::handle handle, float to, float time);
  void fadeRelativePlaySpeed(SoLoud::handle handle, float to, float time);
  void schedulePause(SoLoud::handle handle, float time);
  void scheduleStop(SoLoud::handle handle, float time);
  void oscillateVolume(SoLoud::handle handle, float from, float to, float time);
  void oscillatePan(SoLoud::handle handle, float from, float to, float time);
  void oscillateRelativePlaySpeed(SoLoud::handle handle, float from, float to,
                                  float time);
  void oscillateGlobalVolume(float from, float to, float time);

  /////////////////////////////////////////
  /// 3D audio
  /////////////////////////////////////////

  void update3dAudio();

  PlayerErrors play3d(unsigned int soundHash, unsigned int &handle, float posX,
                      float posY, float posZ, float velX = 0.0f,
                      float velY = 0.0f, float velZ = 0.0f, float volume = 1.0f,
                      bool paused = 0, unsigned int busId = 0,
                      bool looping = false, double loopingStartAt = 0.0);

  void set3dSoundSpeed(float speed);
  float get3dSoundSpeed();

  void set3dListenerParameters(float posX, float posY, float posZ, float atX,
                               float atY, float atZ, float upX, float upY,
                               float upZ, float velocityX, float velocityY,
                               float velocityZ);
  void set3dListenerPosition(float posX, float posY, float posZ);
  void set3dListenerAt(float atX, float atY, float atZ);
  void set3dListenerUp(float upX, float upY, float upZ);
  void set3dListenerVelocity(float velocityX, float velocityY, float velocityZ);

  void set3dSourceParameters(unsigned int handle, float posX, float posY,
                             float posZ, float velocityX, float velocityY,
                             float velocityZ);
  void set3dSourcePosition(unsigned int handle, float posX, float posY,
                           float posZ);
  void set3dSourceVelocity(unsigned int handle, float velocityX,
                           float velocityY, float velocityZ);
  void set3dSourceMinMaxDistance(unsigned int handle, float minDistance,
                                 float maxDistance);
  void set3dSourceAttenuation(unsigned int handle,
                              unsigned int attenuationModel,
                              float attenuationRolloffFactor);
  void set3dSourceDopplerFactor(unsigned int handle, float dopplerFactor);

  /////////////////////////////////////////
  /// Mixing Bus
  /// https://solhsa.com/soloud/mixbus.html
  /////////////////////////////////////////

  unsigned int createBus();
  void destroyBus(unsigned int busId);
  unsigned int busPlayOnEngine(unsigned int busId, float volume, bool paused);
  int busSetChannels(unsigned int busId, unsigned int channels);
  void busSetVisualizationEnable(unsigned int busId, bool enable);
  float *busCalcFFT(unsigned int busId);
  float *busGetWave(unsigned int busId);
  float busGetApproximateVolume(unsigned int busId, unsigned int channel);
  void busAnnexSound(unsigned int busId, unsigned int voiceHandle);
  unsigned int busGetActiveVoiceCount(unsigned int busId);
  BusData *findBusData(unsigned int busId);

  // Fork-specific bus methods: filter management and 3D playback on bus
  PlayerErrors playOnBus(unsigned int busId, unsigned int soundHash,
                         unsigned int &handle, float volume = 1.0f,
                         float pan = 0.0f, bool paused = false,
                         bool looping = false, double loopingStartAt = 0.0);

  PlayerErrors play3dOnBus(unsigned int busId, unsigned int soundHash,
                           unsigned int &handle, float posX, float posY,
                           float posZ, float velX = 0.0f, float velY = 0.0f,
                           float velZ = 0.0f, float volume = 1.0f,
                           bool paused = false, bool looping = false,
                           double loopingStartAt = 0.0);

  void setBusVolume(unsigned int busId, float volume);
  PlayerErrors addBusFilter(unsigned int busId, FilterType filterType);
  PlayerErrors removeBusFilter(unsigned int busId, FilterType filterType);
  void setBusFilterParameter(unsigned int busId, FilterType filterType,
                             int attributeId, float value);
  float getBusFilterParameter(unsigned int busId, FilterType filterType,
                              int attributeId);
  PlayerErrors loadBusConvolutionIR(unsigned int busId, const char *irPath);
  void annexSoundToBus(unsigned int busId, unsigned int voiceHandle);

public:
  /// all the sounds loaded
  std::vector<std::unique_ptr<ActiveSound>> sounds;

  /// true when the backend is initialized
  bool mInited;

  /// main SoLoud engine
  SoLoud::Soloud soloud;

  /// speech object
  SoLoud::Speech speech;

  /// Global filters
  Filters mFilters;

  unsigned int mSampleRate;

  unsigned int mChannels;

private:
  ma_device_info *pPlaybackInfos;
  std::mutex remove_handle_mutex;
  mutable std::recursive_mutex sounds_mutex;
  unsigned int mBufferSize;

  std::map<unsigned int, BusData> busMap;
  unsigned int busIdCounter = 0;
};

#endif // PLAYER_H
